name: 🐛Bug Report
description: Issue for a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Remember to be clear and concise when you explain the issue
  - type: dropdown
    id: Project
    attributes:
      label: Which project is the problem occurring?
      multiple: true
      options:
        - Kiosco
        - Dashboard
        - Monorepo
    validations:
      required: true
  - type: textarea
    id: todo-ids
    attributes:
      label: Todo's codes
      description: Place here the todo's related to the bug
      placeholder: CJEA-ddmmyy-HHmm
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A detailed, concise and accurate description of the problem, including any relevant context or information.
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: Expected-performance
    attributes:
      label: Expected performance
      description: A description of how the feature should work or how the problem should be resolved.
  - type: textarea
    id: Current-performance
    attributes:
      label: Current performance
      description: A description of how the feature is currently working or how the problem is currently occurring.
