name: 游냍Bug Report
description: Issue for a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Recuerda ser claro y conciso cuando expliques el problema
  - type: dropdown
    id: Project
    attributes:
      label: 쮼n qu칠 proyecto se produce el problema?
      multiple: true
      options:
        - Kiosco
        - Dashboard
        - Monorepo
    validations:
      required: true
  - type: input
    id: todo-ids
    attributes:
      label: Todo's
      description: "Anote los Todo's relacionados con el problema."
      placeholder: CJEA-ddmmyy-HHmm
  - type: textarea
    id: what-happened
    attributes:
      label: 쮺ual es el bug 游냍?
      description: "Incluya detalles sobre el problema o la solicitud, incluyendo el contexto relevante y los pasos para reproducir el problema o implementar la solicitud."
      placeholder: Cuando intento cargar la p치gina de inicio, obtengo un error "404 Not Found". Esto sucede en todos los navegadores que he probado (Chrome, Firefox, Edge).
    validations:
      required: true
  - type: textarea
    id: Expected-performance
    attributes:
      label: Comportamiento esperado
      description: Describa c칩mo deber칤a funcionar la caracter칤stica o c칩mo deber칤a solucionarse el problema.
      placeholder: La p치gina de inicio deber칤a cargarse correctamente.
  - type: textarea
    id: Current-performance
    attributes:
      label: Comportamiento actual
      description: Describa c칩mo est치 funcionando actualmente la caracter칤stica o c칩mo se presenta actualmente el problema.
      placeholder: La p치gina de inicio muestra un error "404 Not Found".
